import Link from 'next/link'

import { Icon } from '@/components/icon'
import { FadeIn, Stagger, StaggerItem } from '@/components/motion'

/**
 * The front door — deliberately minimal.
 *
 * One purpose statement and exactly two entrances, clearly separated: the
 * client workspace and the operator (super-admin) console. Everything else
 * lives behind a sign-in.
 */
export const metadata = {
  title: 'VSP — AI Marketing OS',
  description:
    'The AI marketing operating system: campaigns generated, approved, published and measured — for every client, in one place.',
}

export default function LandingPage() {
  return (
    <div
      className="center-screen"
      style={{ flexDirection: 'column', display: 'flex', justifyContent: 'center' }}
    >
      <Stagger interval={0.09} style={{ width: '100%', maxWidth: 880, padding: '0 20px' }}>
        {/* Brand + motive */}
        <StaggerItem style={{ textAlign: 'center', marginBottom: 40 }}>
          <div
            className="brand"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 12,
              fontSize: 22,
              fontWeight: 700,
              letterSpacing: '-0.02em',
              marginBottom: 18,
            }}
          >
            <span className="dot" style={{ width: 34, height: 34, borderRadius: 10 }} />
            VSP
          </div>
          <h1 style={{ fontSize: 'clamp(26px, 4vw, 38px)', letterSpacing: '-0.03em' }}>
            The AI Marketing <span className="grad-text">Operating System</span>
          </h1>
          <p
            className="muted"
            style={{ fontSize: 15.5, maxWidth: 520, margin: '12px auto 0', lineHeight: 1.6 }}
          >
            Campaigns generated by AI, approved by you, published everywhere, measured to the last
            click.
          </p>
        </StaggerItem>

        {/* Exactly two entrances. */}
        <StaggerItem>
          <div className="cols-2 split grid" style={{ gap: 18 }}>
            <Link
              href="/login"
              className="card"
              style={{ padding: 28, textAlign: 'center', display: 'block' }}
            >
              <span
                className="state-badge"
                style={{ width: 54, height: 54, borderRadius: 16, marginBottom: 14 }}
              >
                <Icon name="megaphone" size={24} />
              </span>
              <h2 style={{ fontSize: 18, marginBottom: 6 }}>Client sign in</h2>
              <p className="muted" style={{ fontSize: 13, lineHeight: 1.55, marginBottom: 18 }}>
                Your marketing workspace — campaigns, creatives, leads and results.
              </p>
              <span className="btn primary" style={{ width: '100%', justifyContent: 'center' }}>
                Sign in to your workspace
              </span>
            </Link>

            <Link
              href="/platform/login"
              className="card"
              style={{ padding: 28, textAlign: 'center', display: 'block' }}
            >
              <span
                className="state-badge"
                style={{ width: 54, height: 54, borderRadius: 16, marginBottom: 14 }}
              >
                <Icon name="shield" size={24} />
              </span>
              <h2 style={{ fontSize: 18, marginBottom: 6 }}>Operator console</h2>
              <p className="muted" style={{ fontSize: 13, lineHeight: 1.55, marginBottom: 18 }}>
                Super-admin — onboard clients, manage modules, watch the portfolio.
              </p>
              <span className="btn" style={{ width: '100%', justifyContent: 'center' }}>
                Operator sign in
              </span>
            </Link>
          </div>
        </StaggerItem>

        <StaggerItem>
          <FadeIn delay={0.2}>
            <p className="dim" style={{ textAlign: 'center', fontSize: 12.5, marginTop: 36 }}>
              VSP — AI Marketing OS
            </p>
          </FadeIn>
        </StaggerItem>
      </Stagger>
    </div>
  )
}
