/**
 * Runway media adapter — text-to-image and video generation via Runway's developer
 * API (api.dev.runwayml.com).
 *
 * Operator-level, exactly like `openai-media.ts`: the caller passes a Bearer key
 * already resolved from the platform environment (`RUNWAY_API_KEY`), never a stored
 * per-tenant credential. Any non-2xx response becomes an `AdapterError` so the
 * controller maps it to a generic 503 without ever leaking Runway's error text.
 *
 * Two facts of Runway's API shape this file:
 *   1. Video here is text_to_image → image_to_video. That used to be forced:
 *      there was no text-to-video endpoint. **There is one now** — `/v1/text_to_video`
 *      — so this is a workaround that has outlived its reason, kept for the
 *      moment because the two-step path also yields the seed frame the review
 *      screen uses as a poster. Do not re-derive the old justification from this
 *      code: if the seed frame stops being wanted, the single call is available.
 *   2. Generation is asynchronous. A POST returns a task id; the result is polled
 *      from GET /v1/tasks/{id} until it SUCCEEDs. Runway asks callers not to poll
 *      more than once every five seconds.
 *
 * **Runway's URLs are ephemeral and never leave this file.** Every generated
 * asset is copied into our own storage before the result is returned, and what
 * callers receive is our URL. The adapter cannot do that itself without becoming
 * a Nest service, so persistence arrives as a required `persist` function: a
 * caller that has nowhere to put the bytes cannot compile, which is the only
 * reliable way to stop an expiring link reaching a database row. Assets stored
 * before this existed hold `runwayml.com` URLs and are mostly already dead —
 * see `scripts/backfill-runway-media.ts`.
 */

import { AdapterError } from './llm.js'

const PROVIDER_ID = 'runway'
const BASE_URL = 'https://api.dev.runwayml.com/v1'
// Runway requires this exact version header on every request.
const API_VERSION = '2024-11-06'

const DEFAULT_IMAGE_MODEL = 'gen4_image'
const DEFAULT_VIDEO_MODEL = 'gen4_turbo'

/**
 * The two models accept different ratio lists, and sharing one value between
 * them was wrong.
 *
 * `1280:720` is a gen4_turbo (video) ratio. gen4_image does not accept it —
 * its landscape 16:9 option is `1920:1080` — so every poster request was
 * rejected outright, in about half a second, long before any image was drawn.
 * The old comment asserted the value was "valid for both"; it was never
 * checked against a live call, and the generic 503 the controller returned
 * hid the provider's complaint for as long as the assumption survived.
 *
 * Both defaults are still 16:9, which is what that comment was actually
 * reaching for: the seed frame and the video it animates keep the same shape.
 */
export const DEFAULT_IMAGE_RATIO = '1920:1080'
export const DEFAULT_VIDEO_RATIO = '1280:720'
const DEFAULT_VIDEO_DURATION = 5

/**
 * The image ratio whose shape matches each video ratio.
 *
 * Video is produced as text_to_image → image_to_video, so the seed frame is
 * generated by the *image* model and must use a ratio the image model accepts.
 * Passing the video's ratio straight through — which is what this file used to
 * do — fails on the very first call.
 *
 * Every pair here is the same aspect to within a rounding error, so the seed
 * frame and the clip it becomes are the same shape. An unrecognised video ratio
 * falls back to the default rather than guessing.
 */
export const SEED_FRAME_RATIO = new Map([
  ['1280:720', '1920:1080'], // 16:9 landscape
  ['720:1280', '1080:1920'], // 9:16 portrait
  ['1104:832', '1440:1080'], // 4:3 landscape
  ['832:1104', '1080:1440'], // 3:4 portrait
  ['960:960', '1080:1080'], // square
  ['1584:672', '1808:768'], // 21:9 ultrawide
])

/**
 * Runway's documented ceiling on `promptText`. Exceeding it is a flat 400
 * "Validation of body failed" — no partial generation, no hint as to which
 * field was at fault.
 *
 * The clamp here is a backstop, not the strategy. A caller with a long prompt
 * should decide for itself what to keep, because the end of a prompt is often
 * where its constraints live and blind truncation deletes exactly those. See
 * `clampImagePrompt` in scene-prompt.ts, which preserves the no-text clause.
 */
export const MAX_PROMPT_CHARS = 1000

/** Runway's ceiling for `text_to_image`. More are accepted by the type, not the API. */
const MAX_REFERENCE_IMAGES = 3

/** Trim to the limit on a word boundary, so a prompt never ends mid-word. */
function clampPrompt(text: string): string {
  if (text.length <= MAX_PROMPT_CHARS) return text
  const cut = text.slice(0, MAX_PROMPT_CHARS)
  const lastSpace = cut.lastIndexOf(' ')
  return lastSpace > 0 ? cut.slice(0, lastSpace) : cut
}

// Runway asks for no more than one poll per 5s. A Gen-4 image lands in ~10-30s and
// a short clip in ~60-180s, so we cap generously and then give up cleanly.
const POLL_INTERVAL_MS = 5_000
const IMAGE_TIMEOUT_MS = 120_000
const VIDEO_TIMEOUT_MS = 300_000

function headers(apiKey: string): Record<string, string> {
  return {
    'content-type': 'application/json',
    authorization: `Bearer ${apiKey}`,
    'x-runway-version': API_VERSION,
  }
}

/** Parse a Runway error body into an `AdapterError`, mirroring `openai-media.ts`. */
async function readError(res: Response): Promise<AdapterError> {
  let detail = `${PROVIDER_ID} request failed (${String(res.status)})`
  try {
    const body = (await res.json()) as { error?: string; message?: string }
    const msg = body?.error ?? body?.message
    if (typeof msg === 'string' && msg.length > 0) detail = msg
  } catch {
    // Body was not JSON; keep the generic detail.
  }
  return new AdapterError(detail, PROVIDER_ID, res.status)
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

interface TaskResponse {
  readonly id?: string
  readonly status?: string
  readonly output?: unknown
  readonly failure?: string
}

/** Create a generation task and return its id. */
async function createTask(apiKey: string, path: string, body: unknown): Promise<string> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: 'POST',
    headers: headers(apiKey),
    body: JSON.stringify(body),
  })
  if (!res.ok) throw await readError(res)
  const data = (await res.json()) as TaskResponse
  if (typeof data.id !== 'string' || data.id.length === 0) {
    throw new AdapterError(`${PROVIDER_ID} returned no task id`, PROVIDER_ID)
  }
  return data.id
}

/**
 * Poll a task to completion and return its output URLs. Throws on a terminal
 * failure state or when the deadline passes.
 */
async function pollTask(apiKey: string, taskId: string, timeoutMs: number): Promise<string[]> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    // A freshly created task is never ready before one interval; wait first.
    await sleep(POLL_INTERVAL_MS)
    const res = await fetch(`${BASE_URL}/tasks/${taskId}`, { headers: headers(apiKey) })
    if (!res.ok) throw await readError(res)
    const task = (await res.json()) as TaskResponse

    switch (task.status) {
      case 'SUCCEEDED': {
        const output = Array.isArray(task.output)
          ? task.output.filter((u): u is string => typeof u === 'string')
          : []
        if (output.length === 0) {
          throw new AdapterError(`${PROVIDER_ID} succeeded with no output`, PROVIDER_ID)
        }
        return output
      }
      case 'FAILED':
      case 'CANCELLED':
      case 'EXPIRED':
        throw new AdapterError(
          `${PROVIDER_ID} task ${task.status.toLowerCase()}${task.failure ? `: ${task.failure}` : ''}`,
          PROVIDER_ID,
        )
      default:
        // CREATED / QUEUED / RUNNING / THROTTLED — keep waiting.
        break
    }
  }
  throw new AdapterError(`${PROVIDER_ID} task timed out`, PROVIDER_ID)
}

/**
 * A picture the model is shown before it draws.
 *
 * `tag` is how the prompt refers to it — "@product on a marble table" tells the
 * model which reference is the subject. Runway accepts letters, digits and
 * underscores, up to 16 characters, and the tag must appear in the prompt or the
 * reference is ignored silently.
 *
 * The uri must be reachable by Runway's servers: a public storage URL or a data
 * URI. A signed URL that expires between the request and the render fails at
 * their end, not ours.
 */
/**
 * Copies a freshly generated asset into durable storage and returns our URL.
 *
 * The `key` is supplied by the caller and must be **stable for the same asset**,
 * because the upload upserts: regenerating writes over the previous object
 * instead of leaving an orphan behind. A timestamped key would make every retry
 * a new file that nothing references and nothing deletes.
 *
 * It must throw rather than degrade. The storage service's own `persist` falls
 * back to the source URL when the bucket is unconfigured, which is a reasonable
 * default elsewhere and precisely the failure mode this exists to prevent — so
 * callers pass a wrapper that treats a non-persisted result as an error.
 */
export type PersistMedia = (sourceUrl: string, key: string) => Promise<string>

export interface RunwayReferenceImage {
  readonly uri: string
  readonly tag: string
}

export interface RunwayImageInput {
  readonly apiKey: string
  readonly prompt: string
  readonly ratio?: string
  readonly model?: string
  /** Required. See PersistMedia — an unpersisted URL must never reach a caller. */
  readonly persist: PersistMedia
  /** Stable per asset, so a re-run overwrites rather than orphans. */
  readonly storageKey: string
  /**
   * Up to three images the model should work from.
   *
   * This is what separates a product shot from a stock photograph: without a
   * reference the model invents a plausible latte, with one it photographs the
   * latte that was uploaded. The likeness is strong but not exact — the model
   * redraws rather than composites — which is why the caller decides whether a
   * product may be reshot.
   */
  readonly referenceImages?: readonly RunwayReferenceImage[]
}

export interface RunwayImageResult {
  /** A hosted URL. Runway returns URLs, not inline data; they are ephemeral. */
  readonly url: string
  readonly model: string
}

/** Generate an image from text via Runway's `text_to_image`. */
export async function generateRunwayImage(input: RunwayImageInput): Promise<RunwayImageResult> {
  const model = input.model ?? DEFAULT_IMAGE_MODEL
  const references = (input.referenceImages ?? []).slice(0, MAX_REFERENCE_IMAGES)
  const taskId = await createTask(input.apiKey, '/text_to_image', {
    model,
    promptText: clampPrompt(input.prompt),
    ratio: input.ratio ?? DEFAULT_IMAGE_RATIO,
    // Omitted entirely when empty. Runway rejects `referenceImages: []` rather
    // than treating it as absent, which turns a plain text render into a 400.
    ...(references.length > 0
      ? { referenceImages: references.map((r) => ({ uri: r.uri, tag: r.tag })) }
      : {}),
  })
  const [url] = await pollTask(input.apiKey, taskId, IMAGE_TIMEOUT_MS)
  if (!url) throw new AdapterError(`${PROVIDER_ID} returned no image URL`, PROVIDER_ID)
  return { url: await keep(input.persist, url, input.storageKey), model }
}

/**
 * Copy into our storage, and refuse to return anything that is still Runway's.
 *
 * The second check is not paranoia about the storage service — it is about the
 * next person who writes a `persist` that falls back on error because that felt
 * safer. The row would then hold a link that works all afternoon and 404s by the
 * weekend, and nothing would have failed at the time it could still be fixed.
 */
async function keep(persist: PersistMedia, sourceUrl: string, key: string): Promise<string> {
  const stored = await persist(sourceUrl, key)
  if (!stored) {
    throw new AdapterError(`${PROVIDER_ID} output could not be stored`, PROVIDER_ID)
  }
  if (stored === sourceUrl || /runwayml\.com/i.test(stored)) {
    throw new AdapterError(
      `${PROVIDER_ID} output was not copied into storage — the returned URL is still the provider's and would expire`,
      PROVIDER_ID,
    )
  }
  return stored
}

export interface RunwayVideoInput {
  readonly apiKey: string
  readonly prompt: string
  /** Seed image URL. When absent, a first frame is generated from the prompt. */
  readonly promptImage?: string
  readonly ratio?: string
  readonly duration?: number
  readonly model?: string
  readonly imageModel?: string
  readonly persist: PersistMedia
  /**
   * Stable per asset. The seed frame is stored beside it under `<key>-frame`,
   * so a regeneration overwrites both rather than accumulating pairs.
   */
  readonly storageKey: string
}

export interface RunwayVideoResult {
  readonly url: string
  readonly model: string
}

/**
 * Generate a video from a text prompt via Runway. Because Runway has no
 * text-to-video endpoint, a first frame is synthesised from the prompt with
 * `text_to_image` and then animated with `image_to_video`.
 */
export async function generateRunwayVideo(input: RunwayVideoInput): Promise<RunwayVideoResult> {
  const model = input.model ?? DEFAULT_VIDEO_MODEL
  const ratio = input.ratio ?? DEFAULT_VIDEO_RATIO

  // The seed frame is persisted too, and deliberately: it is the poster frame
  // the review screen shows, and Runway's copy of it expires on the same clock
  // as the video. Handing our own URL to image_to_video also means Runway
  // fetches from a bucket that will still be there on a retry.
  const promptImage =
    input.promptImage ??
    (
      await generateRunwayImage({
        apiKey: input.apiKey,
        prompt: input.prompt,
        // The seed frame's ratio, not the video's — see SEED_FRAME_RATIO.
        ratio: SEED_FRAME_RATIO.get(ratio) ?? DEFAULT_IMAGE_RATIO,
        ...(input.imageModel ? { model: input.imageModel } : {}),
        persist: input.persist,
        storageKey: `${input.storageKey}-frame`,
      })
    ).url

  const taskId = await createTask(input.apiKey, '/image_to_video', {
    model,
    promptImage,
    promptText: clampPrompt(input.prompt),
    ratio,
    duration: input.duration ?? DEFAULT_VIDEO_DURATION,
  })
  const [url] = await pollTask(input.apiKey, taskId, VIDEO_TIMEOUT_MS)
  if (!url) throw new AdapterError(`${PROVIDER_ID} returned no video URL`, PROVIDER_ID)
  return { url: await keep(input.persist, url, input.storageKey), model }
}
